name: Secure CI/CD Pipeline for TODO App

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to DockerHub securely
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build & Push Backend
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:secure

      # Step 5: Build & Push Frontend
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:secure

      # Step 6: Trigger Deployment on Render.com (optional)
      - name: Trigger Render Deployment (Frontend)
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_WEBHOOK_URL || 'https://example.com/webhook' }}

      - name: Trigger Render Deployment (Backend)
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_WEBHOOK_URL || 'https://example.com/webhook' }}
